### ISSUE TITLE
Remove dependency on electrolyzer repo

### ISSUE THREAD

**Issue by johnjasa** [NREL/GreenHEART#29]
Currently, most of the files in GreenHEART use the built-in electrolyzer models.
There's some usage of the electrolyzer repo, leading to a requirement to pip install from Jared's fork.
The cases that use that electrolyzer repo are not necessary; remove that repo and any usage of it from GreenHEART for now and move those to a project repo.

**Comment by jaredthomas68** [comment]
Closing this issue as it was addressed in #33
